<?php
namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;


/**
 * Class FrontendController
 * @package frontend\controllers
 */
class FrontendController extends Controller
{
    /**
     * @inheritdoc
     */
    public function beforeAction($action)
    {
        if (Yii::$app->getUser()->getIsGuest()) {
            throw new ForbiddenHttpException();
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}
